### ISSUE TITLE
Cannot create directory with '/' in the name

### ISSUE THREAD

**Issue by sattellite** [jordoncm/youtube-dl-playlist#1]
$ youtube-dl-playlist 71B8152559FA2805
Getting playlist information ... done
Total videos to download: 141
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl-playlist", line 78, in <module>
    ACTUAL_PATH = createPath(DESTINATION_PATH, data['feed']['title']['$t'])
  File "/usr/local/bin/youtube-dl-playlist", line 47, in createPath
    os.mkdir(path + title + str(number))
OSError: [Errno 2] No such file or directory: './UKF Dubstep (2009/2010)'

**Comment by jordoncm** [comment]
This is an error that occurs if the playlist name has a "/" in the title. I set the script to look for and strip them in the names.

**Comment by sattellite** [comment]
Thanks
