### ISSUE TITLE
Close project

### ISSUE THREAD

**Issue by boiko-danylo** [jordoncm/youtube-dl-playlist#13]
youtube-dl can download playlists.

**Comment by MrYakobo** [comment]
This script also uses the decaprated [gdata.youtube.com](http://gdata.youtube.com) to fetch the links to the videos. As said by @5n00p4eg, this project can safely close as it doesn't really contribute much to anything (but I gotta say that the snippets for installing youtube-dl was kinda handy)

**Comment by jordoncm** [comment]
Yes, this project is old and not useful anymore as youtube-dl now has direct playlist support and the YouTube API changed and broke the code here anyway. Closing.
