### ISSUE TITLE
what am i doing wrong?:(

### ISSUE THREAD

**Issue by juliangitz** [jordoncm/youtube-dl-playlist#15]
$ youtube-dl-playlist PLiaHhY2iBX9g6KIvZ_703G3KJXapKkNaF
Getting playlist information ... 
Error: Not a valid/public playlist.

i get this error everytime

**Comment by justinTM** [comment]
+1 I'm getting this error as well

**Comment by jordoncm** [comment]
youtube-dl added support for playlists years ago. Please use that instead. You are seeing this error because the underlying YouTube API changed. This project is defunct.
