### ISSUE TITLE
"Error: Not a valid/public playlist."

### ISSUE THREAD

**Issue by justinTM** [jordoncm/youtube-dl-playlist#16]
No matter what format I use, I cannot get this command to work:
`youtube-dl-playlist "PLRyrSgHZaoQo8J-tNjbWLW3SnfkJoJZze" /Users/justinmai/Music/`

The playlist is set to "Public" and I have tried multiple paths and even surrounding the playlist ID with quotations (not sure why but I tried it...).

The result is the same:
```
Getting playlist information ... 
Error: Not a valid/public playlist.
```

**Comment by jordoncm** [comment]
youtube-dl added support for playlists years ago. Please use that instead. You are seeing this error because the underlying YouTube API changed. This project is defunct.
