### ISSUE TITLE
os.mkdir (on windows?)

### ISSUE THREAD

**Issue by 5shekel** [jordoncm/youtube-dl-playlist#2]
hi, and thanks for the script 
im getting this error
```M:\bin\youtube-dl>python youtube-dl-playlist PL1F076D1A98071E24
Getting playlist information ... done
Total videos to download: 40
Traceback (most recent call last):
  File "youtube-dl-playlist", line 87, in <module>
    os.mkdir('/tmp/youtube-dl-playlist')
WindowsError: [Error 3] The system cannot find the path specified: '/tmp/youtube-dl-playlist'

```
changing  os.mkdir to os.makedirs works.
still cant d/l that playlist for somereason, but i suspect its something to do with youtube-dl itself..
```

**Comment by jordoncm** [comment]
Try creating a folder called C:\tmp and trying the script again. This script tries to use the tmp folder to do temporary data storage. I will try to add code to look for a writable folder that is compatible for Windows.

Also, I would be surprised if youtube-dl runs on Windows (not sure though). If installing Linux is not an option you could always boot a live CD/USB stick of Linux and use the script, transfer the videos to an external drive and then boot back into Windows.

**Comment by 5shekel** [comment]
thanks, youtube-dl works great on windows.  
im using rg3.github.com/youtube-dl which has playlist support.
