### ISSUE TITLE
ERROR: no fmt_url_map or conn information found in video info 

### ISSUE THREAD

**Issue by cviedmai** [jordoncm/youtube-dl-playlist#3]
Hi there,

doesn't seem to be working anymore. 
First it tells me correctly how many videos my playlist have so it means it can connect to it.
but when it is trying to download the videos it tells me this for each video:

ERROR: no fmt_url_map or conn information found in video info

hope you can help me!

thanks

cristobal

**Comment by cviedmai** [comment]
ok, seems that was an issue with youtube-dl not with youtube-dl-playlist. You can reado about it here:
https://github.com/rg3/youtube-dl/issues/108

**Comment by jordoncm** [comment]
Yeah, you have to make sure you are running an up to date version of youtube-dl. I believe the latest Ubuntu release (and maybe other distros) shipped with a version that didn't work right.
