### ISSUE TITLE
"filename" is undefined on line 118

### ISSUE THREAD

**Issue by dniku** [jordoncm/youtube-dl-playlist#5]
Python complains about an undefined identifier "filename" on line 118.
https://github.com/jordoncm/youtube-dl-playlist/blob/master/youtube-dl-playlist#L118

**Comment by jordoncm** [comment]
If you get this error it means that the call out to youtube-dl has failed and the video file was not found in the temporary directory I used to cache the file before I rename it into place. My guess is that you are using an out of date version of youtube-dl that is not capturing the file properly.

I can try to add some better error handling in that area.

**Comment by dniku** [comment]
You seem to be right, but the problem is not with an obsolete version of youtube-dl, I screwed up somewhere else. Anyway, you might want to take a look at the fork I created that fixes a number of problems that prevented your script from running on Windows, such as not wrong path separators, not handling illegal characters in file names, etc.
