### ISSUE TITLE
if path have chinese show this error

### ISSUE THREAD

**Issue by hepha** [jordoncm/youtube-dl-playlist#8]
if path have chinese show this error
echo $PWD
/mnt/歌仔戲

Getting playlist information ... 
Total videos to download: 5
Traceback (most recent call last):
  File "/usr/sbin/youtube-dl-playlist", line 118, in <module>
    downloader.download(PLAYLIST_ID);
  File "/usr/sbin/youtube-dl-playlist", line 34, in download
    playlistDir = self.createPath(self.targetDir, data['feed']['title']['$t']);
  File "/usr/sbin/youtube-dl-playlist", line 90, in createPath
    if os.path.exists(path + title) == True and os.path.isdir(path + title) == False:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 9: ordinal not in range(128)

**Comment by sagarpdy** [comment]
I think latest youtube-dl has playlist support (though I haven't used it yet). You can try it till this issue is fixed (by somebody :P)

**Comment by hepha** [comment]
@sagarpdy 
thanks you right
 youtube-dl cant download playlist

**Comment by jordoncm** [comment]
Yes, youtube-dl now supports playlists directly. As such I have kinda given up on maintaining this script a bit.
